apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: ttn-allinone
  name: ttn-allinone
spec:
  replicas: 1
  selector:
    io.kompose.service: discovery
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: discovery
    spec:
      volumes:
        - name: discovery-config
          configMap:
            name: discovery-config
            defaultMode: 420 
        - name: router-config
          configMap:
            name: router-config
            defaultMode: 420
        - name: networkserver-config
          configMap:
            name: networkserver-config
            defaultMode: 420
        - name: broker-config
          configMap:
            name: broker-config
            defaultMode: 420
        - name: handler-config
          configMap:
            name: handler-config
            defaultMode: 420
        - name: ttnctl-cert
          configMap:
            name: ttnctl-cert
            defaultMode: 420
      containers:
      - name: discovery
        args:
        - discovery
        - --config
        - ./.env/discovery/dev.yml
        env:
        - name: TERM
          value: xterm-256color
        - name: TTN_DISCOVERY_REDIS_ADDRESS
          value: redis:6379
        image: 'ttn-openshift:latest'
        ports:
        - containerPort: 1900
        - containerPort: 8080
        resources: {}
        volumeMounts:
          - mountPath: /root/.env/discovery
            name: discovery-config
        workingDir: /root
      - name: router
        args:
        - router
        - --config
        - ./.env/router/dev.yml
        env:
        - name: TERM
          value: xterm-256color
        image: 'ttn-openshift:latest'
        ports:
        - containerPort: 1901
        resources: {}
        volumeMounts:
          - mountPath: /root/.env/router
            name: router-config
        workingDir: /root
      - name: networkserver
        args:
        - networkserver
        - --config
        - ./.env/networkserver/dev.yml
        env:
        - name: TERM
          value: xterm-256color
        - name: TTN_NETWORKSERVER_REDIS_ADDRESS
          value: redis:6379
        image: 'ttn-openshift:latest'
        ports:
        - containerPort: 1903
        resources: {}
        volumeMounts:
          - mountPath: /root/.env/networkserver
            name: networkserver-config
        workingDir: /root
      - name: broker
        args:
        - broker
        - --config
        - ./.env/broker/dev.yml
        env:
        - name: TERM
          value: xterm-256color
        image: 'ttn-openshift:latest'
        ports:
        - containerPort: 1902
        resources: {}
        volumeMounts:
          - mountPath: /root/.env/broker
            name: broker-config
        workingDir: /root
      - name: handler
        args:
        - handler
        - --config
        - ./.env/handler/dev.yml
        env:
        - name: TERM
          value: xterm-256color
        - name: TTN_HANDLER_MQTT_ADDRESS
          value: broker-amq-mqtt:1883
        - name: TTN_HANDLER_REDIS_ADDRESS
          value: redis:6379
        image: 'ttn-openshift:latest'
        ports:
        - containerPort: 1904
        - containerPort: 8084
        resources: {}
        volumeMounts:
          - mountPath: /root/.env/handler
            name: handler-config
        workingDir: /root
      - name: ttnctl
        image: 'ttnctl:latest'
        resources: {}
        env:
          - name: TTNCTL_DISCOVERY_ADDRESS
            value: 'localhost:1900'
          - name: TTNCTL_MQTT_ADDRESS
            value: 'broker-amq-mqtt:1883'
          - name: TTNCTL_MQTT_USERNAME
            value: ttn
          - name: TTNCTL_MQTT_PASSWORD
            value: ttn
          - name: TTNCTL_ROUTER_ID
            value: dev
          - name: TTNCTL_HANDLER_ID
            value: dev
          - name: TTNCTL_DATA
            value: data_ttnctl
        volumeMounts:
          - mountPath: /opt/app-root/.ttnctl
            name: ttnctl-cert
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - discovery
      - router
      - networkserver
      - broker
      - handler
      from:
        kind: ImageStreamTag
        name: ttn-openshift:latest
    type: ImageChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - ttnctl
      from:
        kind: ImageStreamTag
        name: ttnctl:latest
    type: ImageChange
status: {}
