apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: handler
  name: handler
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: thethingsnetwork/ttn
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
