apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: networkserver
  name: networkserver
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: thethingsnetwork/ttn
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
